// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/pb/manager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create or fetching existing Spark Connect session
type ConnectSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"` // Additional fields can be added here, when needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSessionRequest) Reset() {
	*x = ConnectSessionRequest{}
	mi := &file_internal_pb_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSessionRequest) ProtoMessage() {}

func (x *ConnectSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSessionRequest.ProtoReflect.Descriptor instead.
func (*ConnectSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

// Spark Connect session details
type ConnectSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionName   string                 `protobuf:"bytes,2,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"` // Additional fields can be added here, when needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSession) Reset() {
	*x = ConnectSession{}
	mi := &file_internal_pb_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSession) ProtoMessage() {}

func (x *ConnectSession) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSession.ProtoReflect.Descriptor instead.
func (*ConnectSession) Descriptor() ([]byte, []int) {
	return file_internal_pb_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectSession) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type ConnectSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSessionListRequest) Reset() {
	*x = ConnectSessionListRequest{}
	mi := &file_internal_pb_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSessionListRequest) ProtoMessage() {}

func (x *ConnectSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSessionListRequest.ProtoReflect.Descriptor instead.
func (*ConnectSessionListRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectSessionListRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ConnectSessionListRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ConnectSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ConnectSession      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	TotalSessions int32                  `protobuf:"varint,2,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	PageNumber    int32                  `protobuf:"varint,3,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSessionListResponse) Reset() {
	*x = ConnectSessionListResponse{}
	mi := &file_internal_pb_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSessionListResponse) ProtoMessage() {}

func (x *ConnectSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSessionListResponse.ProtoReflect.Descriptor instead.
func (*ConnectSessionListResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectSessionListResponse) GetSessions() []*ConnectSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ConnectSessionListResponse) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *ConnectSessionListResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ConnectSessionListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_internal_pb_manager_proto protoreflect.FileDescriptor

const file_internal_pb_manager_proto_rawDesc = "" +
	"\n" +
	"\x19internal/pb/manager.proto\x12\x02pb\":\n" +
	"\x15ConnectSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"R\n" +
	"\x0eConnectSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fsession_name\x18\x02 \x01(\tR\vsessionName\"l\n" +
	"\x19ConnectSessionListRequest\x12\x1f\n" +
	"\vpage_number\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01B\f\n" +
	"\n" +
	"_page_size\"\xb1\x01\n" +
	"\x1aConnectSessionListResponse\x12.\n" +
	"\bsessions\x18\x01 \x03(\v2\x12.pb.ConnectSessionR\bsessions\x12%\n" +
	"\x0etotal_sessions\x18\x02 \x01(\x05R\rtotalSessions\x12\x1f\n" +
	"\vpage_number\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xa0\x01\n" +
	"\n" +
	"ACSManager\x12C\n" +
	"\x12GetOrCreateSession\x12\x19.pb.ConnectSessionRequest\x1a\x12.pb.ConnectSession\x12M\n" +
	"\fListSessions\x12\x1d.pb.ConnectSessionListRequest\x1a\x1e.pb.ConnectSessionListResponseB4Z2github.com/kalliope-product/acsm-spark/internal/pbb\x06proto3"

var (
	file_internal_pb_manager_proto_rawDescOnce sync.Once
	file_internal_pb_manager_proto_rawDescData []byte
)

func file_internal_pb_manager_proto_rawDescGZIP() []byte {
	file_internal_pb_manager_proto_rawDescOnce.Do(func() {
		file_internal_pb_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_manager_proto_rawDesc), len(file_internal_pb_manager_proto_rawDesc)))
	})
	return file_internal_pb_manager_proto_rawDescData
}

var file_internal_pb_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_manager_proto_goTypes = []any{
	(*ConnectSessionRequest)(nil),      // 0: pb.ConnectSessionRequest
	(*ConnectSession)(nil),             // 1: pb.ConnectSession
	(*ConnectSessionListRequest)(nil),  // 2: pb.ConnectSessionListRequest
	(*ConnectSessionListResponse)(nil), // 3: pb.ConnectSessionListResponse
}
var file_internal_pb_manager_proto_depIdxs = []int32{
	1, // 0: pb.ConnectSessionListResponse.sessions:type_name -> pb.ConnectSession
	0, // 1: pb.ACSManager.GetOrCreateSession:input_type -> pb.ConnectSessionRequest
	2, // 2: pb.ACSManager.ListSessions:input_type -> pb.ConnectSessionListRequest
	1, // 3: pb.ACSManager.GetOrCreateSession:output_type -> pb.ConnectSession
	3, // 4: pb.ACSManager.ListSessions:output_type -> pb.ConnectSessionListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_manager_proto_init() }
func file_internal_pb_manager_proto_init() {
	if File_internal_pb_manager_proto != nil {
		return
	}
	file_internal_pb_manager_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_manager_proto_rawDesc), len(file_internal_pb_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_manager_proto_goTypes,
		DependencyIndexes: file_internal_pb_manager_proto_depIdxs,
		MessageInfos:      file_internal_pb_manager_proto_msgTypes,
	}.Build()
	File_internal_pb_manager_proto = out.File
	file_internal_pb_manager_proto_goTypes = nil
	file_internal_pb_manager_proto_depIdxs = nil
}
