// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: internal/pb/manager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ACSManager_GetOrCreateSession_FullMethodName = "/pb.ACSManager/GetOrCreateSession"
	ACSManager_ListSessions_FullMethodName       = "/pb.ACSManager/ListSessions"
)

// ACSManagerClient is the client API for ACSManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for managing Spark Connect sessions
type ACSManagerClient interface {
	// RPC to create or fetch a Spark Connect session
	GetOrCreateSession(ctx context.Context, in *ConnectSessionRequest, opts ...grpc.CallOption) (*ConnectSession, error)
	// RPC to list all Spark Connect sessions with pagination
	ListSessions(ctx context.Context, in *ConnectSessionListRequest, opts ...grpc.CallOption) (*ConnectSessionListResponse, error)
}

type aCSManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewACSManagerClient(cc grpc.ClientConnInterface) ACSManagerClient {
	return &aCSManagerClient{cc}
}

func (c *aCSManagerClient) GetOrCreateSession(ctx context.Context, in *ConnectSessionRequest, opts ...grpc.CallOption) (*ConnectSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectSession)
	err := c.cc.Invoke(ctx, ACSManager_GetOrCreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCSManagerClient) ListSessions(ctx context.Context, in *ConnectSessionListRequest, opts ...grpc.CallOption) (*ConnectSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectSessionListResponse)
	err := c.cc.Invoke(ctx, ACSManager_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ACSManagerServer is the server API for ACSManager service.
// All implementations must embed UnimplementedACSManagerServer
// for forward compatibility.
//
// Service definition for managing Spark Connect sessions
type ACSManagerServer interface {
	// RPC to create or fetch a Spark Connect session
	GetOrCreateSession(context.Context, *ConnectSessionRequest) (*ConnectSession, error)
	// RPC to list all Spark Connect sessions with pagination
	ListSessions(context.Context, *ConnectSessionListRequest) (*ConnectSessionListResponse, error)
	mustEmbedUnimplementedACSManagerServer()
}

// UnimplementedACSManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedACSManagerServer struct{}

func (UnimplementedACSManagerServer) GetOrCreateSession(context.Context, *ConnectSessionRequest) (*ConnectSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateSession not implemented")
}
func (UnimplementedACSManagerServer) ListSessions(context.Context, *ConnectSessionListRequest) (*ConnectSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedACSManagerServer) mustEmbedUnimplementedACSManagerServer() {}
func (UnimplementedACSManagerServer) testEmbeddedByValue()                    {}

// UnsafeACSManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ACSManagerServer will
// result in compilation errors.
type UnsafeACSManagerServer interface {
	mustEmbedUnimplementedACSManagerServer()
}

func RegisterACSManagerServer(s grpc.ServiceRegistrar, srv ACSManagerServer) {
	// If the following call panics, it indicates UnimplementedACSManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ACSManager_ServiceDesc, srv)
}

func _ACSManager_GetOrCreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACSManagerServer).GetOrCreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACSManager_GetOrCreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACSManagerServer).GetOrCreateSession(ctx, req.(*ConnectSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACSManager_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACSManagerServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ACSManager_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACSManagerServer).ListSessions(ctx, req.(*ConnectSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ACSManager_ServiceDesc is the grpc.ServiceDesc for ACSManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ACSManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ACSManager",
	HandlerType: (*ACSManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateSession",
			Handler:    _ACSManager_GetOrCreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _ACSManager_ListSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/manager.proto",
}
