# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\x12\x07manager\"-\n\x15\x43onnectSessionRequest\x12\x14\n\x0csession_name\x18\x01 \x01(\t\":\n\x0e\x43onnectSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0csession_name\x18\x02 \x01(\t\"V\n\x19\x43onnectSessionListRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x16\n\tpage_size\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_page_size\"\x87\x01\n\x1a\x43onnectSessionListResponse\x12)\n\x08sessions\x18\x01 \x03(\x0b\x32\x17.manager.ConnectSession\x12\x16\n\x0etotal_sessions\x18\x02 \x01(\x05\x12\x13\n\x0bpage_number\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x32\xb4\x01\n\nACSManager\x12M\n\x12GetOrCreateSession\x12\x1e.manager.ConnectSessionRequest\x1a\x17.manager.ConnectSession\x12W\n\x0cListSessions\x12\".manager.ConnectSessionListRequest\x1a#.manager.ConnectSessionListResponseB9Z7github.com/kalliope-product/acsm-spark/internal/managerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/kalliope-product/acsm-spark/internal/manager'
  _globals['_CONNECTSESSIONREQUEST']._serialized_start=26
  _globals['_CONNECTSESSIONREQUEST']._serialized_end=71
  _globals['_CONNECTSESSION']._serialized_start=73
  _globals['_CONNECTSESSION']._serialized_end=131
  _globals['_CONNECTSESSIONLISTREQUEST']._serialized_start=133
  _globals['_CONNECTSESSIONLISTREQUEST']._serialized_end=219
  _globals['_CONNECTSESSIONLISTRESPONSE']._serialized_start=222
  _globals['_CONNECTSESSIONLISTRESPONSE']._serialized_end=357
  _globals['_ACSMANAGER']._serialized_start=360
  _globals['_ACSMANAGER']._serialized_end=540
# @@protoc_insertion_point(module_scope)
