# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import acsm_spark.manager_pb2 as manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ACSManagerStub(object):
    """Service definition for managing Spark Connect sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrCreateSession = channel.unary_unary(
                '/manager.ACSManager/GetOrCreateSession',
                request_serializer=manager__pb2.ConnectSessionRequest.SerializeToString,
                response_deserializer=manager__pb2.ConnectSession.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/manager.ACSManager/ListSessions',
                request_serializer=manager__pb2.ConnectSessionListRequest.SerializeToString,
                response_deserializer=manager__pb2.ConnectSessionListResponse.FromString,
                _registered_method=True)


class ACSManagerServicer(object):
    """Service definition for managing Spark Connect sessions
    """

    def GetOrCreateSession(self, request, context):
        """RPC to create or fetch a Spark Connect session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """RPC to list all Spark Connect sessions with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ACSManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrCreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreateSession,
                    request_deserializer=manager__pb2.ConnectSessionRequest.FromString,
                    response_serializer=manager__pb2.ConnectSession.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=manager__pb2.ConnectSessionListRequest.FromString,
                    response_serializer=manager__pb2.ConnectSessionListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manager.ACSManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manager.ACSManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ACSManager(object):
    """Service definition for managing Spark Connect sessions
    """

    @staticmethod
    def GetOrCreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.ACSManager/GetOrCreateSession',
            manager__pb2.ConnectSessionRequest.SerializeToString,
            manager__pb2.ConnectSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.ACSManager/ListSessions',
            manager__pb2.ConnectSessionListRequest.SerializeToString,
            manager__pb2.ConnectSessionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
